// ─── Legal Document System ────────────────────────────────────────────────────
// All intercompany and employment legal documents for Wavult Group.
// Documents are generated by the system and proposed proactively when
// the system detects a legal need (new entity, new role, capital flow, etc.)

export type SigningLevel = 'L1' | 'L2' | 'L3'
export type DocStatus = 'proposed' | 'draft' | 'pending_signature' | 'signed' | 'expired' | 'rejected'
export type SignMethod = 'click' | 'email_otp' | 'bankid' | 'eid_eidas' | 'docusign'

export interface LegalDocument {
  id: string
  type: LegalDocType
  title: string
  party_a: string          // entity_id from org-graph data
  party_b: string          // entity_id from org-graph data
  signing_level: SigningLevel
  sign_method: SignMethod
  status: DocStatus
  created_at: string       // ISO date
  signed_at?: string
  expires_at?: string
  description: string
  required: boolean        // system considers this mandatory
  auto_proposed: boolean   // was this proposed by the system?
  amount?: number          // for financial agreements
  currency?: string
  royalty_rate?: number    // for IP licenses (percentage)
  notice_period_days?: number
}

export type LegalDocType =
  | 'ip_license'
  | 'management_agreement'
  | 'service_agreement'
  | 'shareholder_agreement'
  | 'intercompany_loan'
  | 'employment_contract'
  | 'nda'
  | 'data_processing_agreement'

export const DOC_TYPE_LABELS: Record<LegalDocType, string> = {
  ip_license: 'IP-licensavtal',
  management_agreement: 'Management Agreement',
  service_agreement: 'Service Agreement',
  shareholder_agreement: 'Aktieägaravtal',
  intercompany_loan: 'Koncernlån',
  employment_contract: 'Anställningsavtal',
  nda: 'Sekretessavtal (NDA)',
  data_processing_agreement: 'Personuppgiftsbiträdesavtal (DPA)',
}

export const SIGNING_LEVEL_LABELS: Record<SigningLevel, string> = {
  L1: 'Intern klick-signatur',
  L2: 'E-signatur (BankID / OTP)',
  L3: 'Kvalificerad signatur (BankID + vittnen)',
}

export const SIGNING_LEVEL_DESCRIPTION: Record<SigningLevel, string> = {
  L1: 'Interna policies och rutindokument',
  L2: 'Anställningsavtal och intercompany-avtal',
  L3: 'Bolagshandlingar, IP-licenser, aktieägaravtal',
}

export const DOC_TYPE_SIGNING_LEVEL: Record<LegalDocType, SigningLevel> = {
  ip_license: 'L3',
  management_agreement: 'L2',
  service_agreement: 'L2',
  shareholder_agreement: 'L3',
  intercompany_loan: 'L2',
  employment_contract: 'L2',
  nda: 'L1',
  data_processing_agreement: 'L2',
}

// ─── Jurisdiction-aware signing method resolution ─────────────────────────────

export function getSignMethodsForJurisdiction(jurisdiction: string, level: SigningLevel): SignMethod[] {
  switch (level) {
    case 'L1': return ['click']
    case 'L2':
      if (jurisdiction === 'SE') return ['bankid', 'email_otp']
      if (['EU-LT', 'EU-DE', 'EU-NL'].includes(jurisdiction)) return ['eid_eidas', 'email_otp']
      return ['email_otp'] // USA, Global, Dubai
    case 'L3':
      if (jurisdiction === 'SE') return ['bankid']
      if (jurisdiction.startsWith('EU')) return ['eid_eidas']
      return ['docusign'] // USA, Global
  }
}

export const SIGN_METHOD_LABELS: Record<SignMethod, string> = {
  click: '🖱️ Klick-signatur',
  email_otp: '📧 E-post OTP',
  bankid: '🇸🇪 BankID',
  eid_eidas: '🇪🇺 eIDAS (Scrive)',
  docusign: '🖊️ DocuSign',
}

// ─── Current legal documents (Wavult Group) ──────────────────────────────────
export const LEGAL_DOCUMENTS: LegalDocument[] = [
  // IP-licenser: Wavult Group (Dubai) → driftsbolag
  {
    id: 'ip-001',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group → Wavult Operations',
    party_a: 'wavult-group',      // Dubai (Global)
    party_b: 'wavult-operations', // Dubai
    signing_level: 'L3',
    sign_method: 'docusign',      // both Dubai → international
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Exklusiv licens för all IP utvecklad inom Wavult Operations. Royalty 5–15% av nettointäkter.',
    required: true,
    auto_proposed: true,
    royalty_rate: 10,
  },
  {
    id: 'ip-002',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group → QuiXzoom UAB',
    party_a: 'wavult-group',      // Dubai
    party_b: 'quixzoom-uab',      // EU-LT
    signing_level: 'L3',
    sign_method: 'eid_eidas',     // party_b is EU → eIDAS
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Icke-exklusiv licens för QuiXzoom-plattformen i EU. Royalty 5% av nettointäkter.',
    required: true,
    auto_proposed: true,
    royalty_rate: 5,
  },
  {
    id: 'ip-003',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group → LandveX Inc',
    party_a: 'wavult-group',      // Dubai
    party_b: 'landvex-inc',       // US-TX
    signing_level: 'L3',
    sign_method: 'docusign',      // US party → DocuSign
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Icke-exklusiv licens för LandveX-plattformen i USA/Texas. Royalty 8% av nettointäkter.',
    required: true,
    auto_proposed: true,
    royalty_rate: 8,
  },
  // Management Agreements
  {
    id: 'ma-001',
    type: 'management_agreement',
    title: 'Management Agreement — Wavult Group → Wavult Operations',
    party_a: 'wavult-group',      // Dubai
    party_b: 'wavult-operations', // Dubai
    signing_level: 'L2',
    sign_method: 'email_otp',     // both Dubai → OTP
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Lednings- och konsulttjänster. Holding tillhandahåller strategisk ledning, juridik, ekonomi och IT.',
    required: true,
    auto_proposed: true,
    amount: 25000,
    currency: 'SEK',
  },
  {
    id: 'ma-002',
    type: 'management_agreement',
    title: 'Management Agreement — Wavult Operations → QuiXzoom UAB',
    party_a: 'wavult-operations', // Dubai
    party_b: 'quixzoom-uab',      // EU-LT
    signing_level: 'L2',
    sign_method: 'eid_eidas',     // EU party → eIDAS
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Operativa lednings- och supporttjänster för QuiXzoom UAB.',
    required: true,
    auto_proposed: true,
    amount: 5000,
    currency: 'EUR',
  },
  // Service Agreements
  {
    id: 'sa-001',
    type: 'service_agreement',
    title: 'Service Agreement — Tech & Platform (Wavult Operations → QuiXzoom UAB)',
    party_a: 'wavult-operations', // Dubai
    party_b: 'quixzoom-uab',      // EU-LT
    signing_level: 'L2',
    sign_method: 'eid_eidas',     // EU party → eIDAS
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Tekniska plattformstjänster: hosting, API, support, underhåll.',
    required: true,
    auto_proposed: true,
    amount: 3000,
    currency: 'EUR',
  },
  {
    id: 'sa-002',
    type: 'service_agreement',
    title: 'Service Agreement — Tech & Platform (Wavult Operations → LandveX Inc)',
    party_a: 'wavult-operations', // Dubai
    party_b: 'landvex-inc',       // US-TX
    signing_level: 'L2',
    sign_method: 'email_otp',     // US party → OTP (DocuSign for L3 only)
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Tekniska plattformstjänster för LandveX US: Optical Insight Cloud US, API, support.',
    required: true,
    auto_proposed: true,
    amount: 2500,
    currency: 'USD',
  },
  // DPA (GDPR requirement — EU entities)
  {
    id: 'dpa-001',
    type: 'data_processing_agreement',
    title: 'Personuppgiftsbiträdesavtal — Wavult Operations ↔ QuiXzoom UAB',
    party_a: 'wavult-operations', // Dubai
    party_b: 'quixzoom-uab',      // EU-LT
    signing_level: 'L2',
    sign_method: 'eid_eidas',     // EU party → eIDAS
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'GDPR-krav: reglerar behandling av personuppgifter mellan EU-bolag.',
    required: true,
    auto_proposed: true,
  },
]

// ─── Proactive legal trigger rules ───────────────────────────────────────────
// The system checks these rules and proposes documents automatically.

export interface LegalTrigger {
  id: string
  description: string
  condition: string     // human-readable condition
  generates: LegalDocType[]
  priority: 'critical' | 'high' | 'medium'
}

export const LEGAL_TRIGGERS: LegalTrigger[] = [
  {
    id: 'new-entity',
    description: 'Nytt bolag kopplas till koncernen',
    condition: 'Entity added with parent_entity_id set',
    generates: ['ip_license', 'management_agreement', 'service_agreement'],
    priority: 'critical',
  },
  {
    id: 'new-employee-foreign',
    description: 'Ny anställd i utländskt bolag',
    condition: 'Employment contract created for non-SE entity',
    generates: ['employment_contract', 'nda'],
    priority: 'high',
  },
  {
    id: 'capital-transfer',
    description: 'Kapitalöverföring mellan bolag',
    condition: 'Intercompany payment > 50,000 SEK',
    generates: ['intercompany_loan'],
    priority: 'high',
  },
  {
    id: 'eu-data-processing',
    description: 'EU-bolag behandlar personuppgifter',
    condition: 'Entity in EU jurisdiction processes user data',
    generates: ['data_processing_agreement'],
    priority: 'critical',
  },
  {
    id: 'external-party',
    description: 'Externt företag/person ska ha tillgång till system',
    condition: 'New external user or vendor added',
    generates: ['nda', 'service_agreement'],
    priority: 'medium',
  },
]
