/**
 * Morning Brief — Wavult Group
 * Enterprise white design, Apple-inspired.
 * Generated by BOS Scheduler and delivered via n8n/SMTP.
 */

export interface MorningBriefParams {
  date: string          // "Måndag 30 mars 2026"
  dayNumber: number     // 7
  totalDays: number     // 30
  daysToThailand: number
  commits: string[]     // senaste git commits (senaste 24h)
  bosHighlights: string[] // top priority tasks från BOS
  quote?: string        // dagens citat (valfritt, roteras)
  systemStatus?: {
    wavultApi: boolean
    quixzoomApi: boolean
    bosScheduler: boolean
  }
}

const DEFAULT_QUOTES = [
  'Bygg det som inte kan ignoreras.',
  'Varje commit är ett steg mot något riktigt.',
  'Disciplin är friheten att göra det som faktiskt spelar roll.',
  'Enkelt är svårt. Gör det enkelt.',
  'Vi sitter inte och väntar på rätt tillfälle — vi skapar det.',
  'Det som mäts förbättras. Det som ignoreras försvinner.',
  'Momentum är dyrt att bygga och billigt att förlora.',
  'Bra kod är ett brev till den som läser det imorgon.',
  'Ingen plan överlever kontakt med verkligheten. Det är okej.',
  'Fart utan riktning är bara larm. Riktning utan fart är bara teori.',
]

function getDefaultQuote(dayNumber: number): string {
  return DEFAULT_QUOTES[dayNumber % DEFAULT_QUOTES.length]
}

function statusDot(live: boolean): string {
  return live
    ? `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#34C759;margin-right:6px;vertical-align:middle;"></span>`
    : `<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#FF3B30;margin-right:6px;vertical-align:middle;"></span>`
}

function statusText(live: boolean): string {
  return live ? 'Live' : 'Down'
}

export function generateMorningBriefHTML(params: MorningBriefParams): string {
  const {
    date,
    dayNumber,
    totalDays,
    daysToThailand,
    commits,
    bosHighlights,
    quote,
    systemStatus = { wavultApi: true, quixzoomApi: true, bosScheduler: true },
  } = params

  const resolvedQuote = quote || getDefaultQuote(dayNumber)

  const commitItems = commits.length > 0
    ? commits.map(c =>
        `<li style="padding:6px 0;border-bottom:1px solid #F2F2F7;font-size:14px;color:#1C1C1E;font-family:ui-monospace,'SF Mono',Menlo,monospace;word-break:break-word;">${escapeHtml(c)}</li>`
      ).join('')
    : `<li style="padding:6px 0;font-size:14px;color:#8E8E93;font-style:italic;">Inga commits hittade senaste 24h</li>`

  const highlightItems = bosHighlights.length > 0
    ? bosHighlights.map(h =>
        `<li style="padding:8px 0 8px 12px;border-left:3px solid #FF9500;margin-bottom:4px;font-size:14px;color:#1C1C1E;list-style:none;">${escapeHtml(h)}</li>`
      ).join('')
    : `<li style="padding:8px 0;font-size:14px;color:#8E8E93;font-style:italic;list-style:none;">Inga aktiva prioriteringar i BOS</li>`

  const thailandProgress = Math.max(0, daysToThailand)
  const thaiLabel = thailandProgress === 0
    ? '🛫 Det är idag!'
    : `${thailandProgress} dagar kvar`

  return `<!DOCTYPE html>
<html lang="sv">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Morning Brief · Wavult Group</title>
  <!--[if mso]>
  <noscript>
    <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
  </noscript>
  <![endif]-->
</head>
<body style="margin:0;padding:0;background-color:#F5F5F7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">

  <!-- Outer wrapper -->
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#F5F5F7;">
    <tr>
      <td align="center" style="padding:32px 16px 48px;">

        <!-- Container -->
        <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;">

          <!-- ── HEADER ── -->
          <tr>
            <td style="padding-bottom:24px;">
              <p style="margin:0 0 4px;font-size:11px;letter-spacing:0.08em;color:#8E8E93;text-transform:uppercase;font-weight:500;">Wavult Group · Morning Brief</p>
              <h1 style="margin:0 0 8px;font-size:22px;font-weight:600;color:#1C1C1E;letter-spacing:-0.3px;">${escapeHtml(date)}</h1>
              <p style="margin:0;font-size:13px;color:#8E8E93;">Dag ${dayNumber} av ${totalDays}</p>
            </td>
          </tr>

          <!-- Thailand badge -->
          <tr>
            <td style="padding-bottom:28px;">
              <span style="display:inline-block;background:#fff;border:1px solid #E5E5EA;border-radius:20px;padding:5px 14px;font-size:12px;color:#3A3A3C;font-weight:500;">
                ✈ Thailand 11 april · ${thaiLabel}
              </span>
            </td>
          </tr>

          <!-- ── CARD: VAD VI BYGGDE IGÅR ── -->
          <tr>
            <td style="padding-bottom:12px;">
              <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #E5E5EA;border-radius:14px;overflow:hidden;">
                <tr>
                  <td style="padding:20px 24px 4px;">
                    <p style="margin:0 0 12px;font-size:11px;letter-spacing:0.1em;color:#8E8E93;text-transform:uppercase;font-weight:600;font-family:ui-monospace,'SF Mono',Menlo,monospace;">Vad vi byggde igår</p>
                    <ul style="margin:0;padding:0;list-style:none;">
                      ${commitItems}
                    </ul>
                  </td>
                </tr>
                <tr><td style="padding:12px 24px 20px;"><span style="font-size:11px;color:#C7C7CC;">Senaste 24h · git log</span></td></tr>
              </table>
            </td>
          </tr>

          <!-- ── CARD: SYSTEM STATUS ── -->
          <tr>
            <td style="padding-bottom:12px;">
              <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #E5E5EA;border-radius:14px;overflow:hidden;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 16px;font-size:11px;letter-spacing:0.1em;color:#8E8E93;text-transform:uppercase;font-weight:600;font-family:ui-monospace,'SF Mono',Menlo,monospace;">System Status</p>
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td style="padding:6px 0;font-size:14px;color:#1C1C1E;width:50%;">
                          ${statusDot(systemStatus.wavultApi)}Wavult API
                        </td>
                        <td style="padding:6px 0;font-size:13px;color:${systemStatus.wavultApi ? '#34C759' : '#FF3B30'};font-weight:500;">
                          ${statusText(systemStatus.wavultApi)}
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:6px 0;font-size:14px;color:#1C1C1E;border-top:1px solid #F2F2F7;">
                          ${statusDot(systemStatus.quixzoomApi)}QuiXzoom API
                        </td>
                        <td style="padding:6px 0;font-size:13px;color:${systemStatus.quixzoomApi ? '#34C759' : '#FF3B30'};font-weight:500;border-top:1px solid #F2F2F7;">
                          ${statusText(systemStatus.quixzoomApi)}
                        </td>
                      </tr>
                      <tr>
                        <td style="padding:6px 0;font-size:14px;color:#1C1C1E;border-top:1px solid #F2F2F7;">
                          ${statusDot(systemStatus.bosScheduler)}BOS Scheduler
                        </td>
                        <td style="padding:6px 0;font-size:13px;color:${systemStatus.bosScheduler ? '#34C759' : '#FF3B30'};font-weight:500;border-top:1px solid #F2F2F7;">
                          ${statusText(systemStatus.bosScheduler)}
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ── CARD: FOKUS IDAG ── -->
          <tr>
            <td style="padding-bottom:12px;">
              <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #E5E5EA;border-radius:14px;overflow:hidden;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 12px;font-size:11px;letter-spacing:0.1em;color:#8E8E93;text-transform:uppercase;font-weight:600;font-family:ui-monospace,'SF Mono',Menlo,monospace;">Fokus idag</p>
                    <ul style="margin:0;padding:0;">
                      ${highlightItems}
                    </ul>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ── CARD: NEDRÄKNING ── -->
          <tr>
            <td style="padding-bottom:12px;">
              <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #E5E5EA;border-radius:14px;overflow:hidden;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 8px;font-size:11px;letter-spacing:0.1em;color:#8E8E93;text-transform:uppercase;font-weight:600;font-family:ui-monospace,'SF Mono',Menlo,monospace;">Nedräkning</p>
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                      <tr>
                        <td>
                          <p style="margin:0;font-size:28px;font-weight:700;color:#1C1C1E;letter-spacing:-0.5px;">${thailandProgress}</p>
                          <p style="margin:4px 0 0;font-size:14px;color:#8E8E93;">dagar till Thailand Workcamp · 11 april 2026</p>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ── CARD: DAGENS ENERGI ── -->
          <tr>
            <td style="padding-bottom:32px;">
              <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border:1px solid #E5E5EA;border-radius:14px;overflow:hidden;">
                <tr>
                  <td style="padding:20px 24px;">
                    <p style="margin:0 0 12px;font-size:11px;letter-spacing:0.1em;color:#8E8E93;text-transform:uppercase;font-weight:600;font-family:ui-monospace,'SF Mono',Menlo,monospace;">Dagens energi</p>
                    <blockquote style="margin:0;padding:0 0 0 14px;border-left:3px solid #007AFF;">
                      <p style="margin:0;font-size:16px;color:#1C1C1E;font-style:italic;line-height:1.5;">"${escapeHtml(resolvedQuote)}"</p>
                    </blockquote>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- ── FOOTER ── -->
          <tr>
            <td style="border-top:1px solid #E5E5EA;padding-top:24px;text-align:center;">
              <p style="margin:0 0 6px;font-size:12px;color:#8E8E93;">Wavult Group · erik@wavult.com</p>
              <p style="margin:0;font-size:11px;color:#C7C7CC;">
                <a href="#" style="color:#C7C7CC;text-decoration:none;">Avregistrera dig</a>
                &nbsp;·&nbsp;
                <a href="https://wavult.com" style="color:#C7C7CC;text-decoration:none;">wavult.com</a>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}
